// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/carloseduribeiro/dependency-injection-with-google-wire/product"
	"github.com/google/wire"
)

import (
	_ "github.com/mattn/go-sqlite3"
)

// Injectors from wire.go:

func NewUseCase(db *sql.DB) *product.UseCase {
	productRepository := product.NewProductRepository(db)
	useCase := product.NewProductUseCase(productRepository)
	return useCase
}

// wire.go:

var setRepositoryDependency = wire.NewSet(product.NewProductRepository, wire.Bind(new(product.RepositoryInterface), new(*product.ProductRepository)))
